# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05hello\"!\n\x0c\x46raudRequest\x12\x11\n\tbank_card\x18\x01 \x01(\t\"\x1f\n\rFraudResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2E\n\x0cHelloService\x12\x35\n\x08SayHello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse2G\n\x0c\x46raudService\x12\x37\n\nFraudCheck\x12\x13.hello.FraudRequest\x1a\x14.hello.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAUDREQUEST']._serialized_start=32
  _globals['_FRAUDREQUEST']._serialized_end=65
  _globals['_FRAUDRESPONSE']._serialized_start=67
  _globals['_FRAUDRESPONSE']._serialized_end=98
  _globals['_HELLOREQUEST']._serialized_start=100
  _globals['_HELLOREQUEST']._serialized_end=128
  _globals['_HELLORESPONSE']._serialized_start=130
  _globals['_HELLORESPONSE']._serialized_end=163
  _globals['_HELLOSERVICE']._serialized_start=165
  _globals['_HELLOSERVICE']._serialized_end=234
  _globals['_FRAUDSERVICE']._serialized_start=236
  _globals['_FRAUDSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
