# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import database_pb2 as database__pb2


class DatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DatabaseReader = channel.unary_unary(
                '/database.DatabaseService/DatabaseReader',
                request_serializer=database__pb2.DatabaseRead.SerializeToString,
                response_deserializer=database__pb2.DatabaseResponse.FromString,
                )
        self.DatabaseWriter = channel.unary_unary(
                '/database.DatabaseService/DatabaseWriter',
                request_serializer=database__pb2.DatabaseWrite.SerializeToString,
                response_deserializer=database__pb2.DatabaseResponse.FromString,
                )
        self.DatabasePreparer = channel.unary_unary(
                '/database.DatabaseService/DatabasePreparer',
                request_serializer=database__pb2.DatabasePrepare.SerializeToString,
                response_deserializer=database__pb2.DatabaseResponse.FromString,
                )
        self.DatabaseCommiter = channel.unary_unary(
                '/database.DatabaseService/DatabaseCommiter',
                request_serializer=database__pb2.DatabaseCommit.SerializeToString,
                response_deserializer=database__pb2.DatabaseResponse.FromString,
                )


class DatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DatabaseReader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DatabaseWriter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DatabasePreparer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DatabaseCommiter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DatabaseReader': grpc.unary_unary_rpc_method_handler(
                    servicer.DatabaseReader,
                    request_deserializer=database__pb2.DatabaseRead.FromString,
                    response_serializer=database__pb2.DatabaseResponse.SerializeToString,
            ),
            'DatabaseWriter': grpc.unary_unary_rpc_method_handler(
                    servicer.DatabaseWriter,
                    request_deserializer=database__pb2.DatabaseWrite.FromString,
                    response_serializer=database__pb2.DatabaseResponse.SerializeToString,
            ),
            'DatabasePreparer': grpc.unary_unary_rpc_method_handler(
                    servicer.DatabasePreparer,
                    request_deserializer=database__pb2.DatabasePrepare.FromString,
                    response_serializer=database__pb2.DatabaseResponse.SerializeToString,
            ),
            'DatabaseCommiter': grpc.unary_unary_rpc_method_handler(
                    servicer.DatabaseCommiter,
                    request_deserializer=database__pb2.DatabaseCommit.FromString,
                    response_serializer=database__pb2.DatabaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'database.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DatabaseReader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/DatabaseReader',
            database__pb2.DatabaseRead.SerializeToString,
            database__pb2.DatabaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DatabaseWriter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/DatabaseWriter',
            database__pb2.DatabaseWrite.SerializeToString,
            database__pb2.DatabaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DatabasePreparer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/DatabasePreparer',
            database__pb2.DatabasePrepare.SerializeToString,
            database__pb2.DatabaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DatabaseCommiter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/database.DatabaseService/DatabaseCommiter',
            database__pb2.DatabaseCommit.SerializeToString,
            database__pb2.DatabaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
