# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0btransaction\"-\n\x12TransactionRequest\x12\x17\n\x0f\x65xpiration_date\x18\x01 \x01(\t\"%\n\x13TransactionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32k\n\x12TransactionService\x12U\n\x10TransactionCheck\x12\x1f.transaction.TransactionRequest\x1a .transaction.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=47
  _globals['_TRANSACTIONREQUEST']._serialized_end=92
  _globals['_TRANSACTIONRESPONSE']._serialized_start=94
  _globals['_TRANSACTIONRESPONSE']._serialized_end=131
  _globals['_TRANSACTIONSERVICE']._serialized_start=133
  _globals['_TRANSACTIONSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
