# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import queue_pb2 as queue__pb2


class QueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueuePropose = channel.unary_unary(
                '/queue.QueueService/QueuePropose',
                request_serializer=queue__pb2.QueueRequest.SerializeToString,
                response_deserializer=queue__pb2.QueueResponse.FromString,
                )


class QueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueuePropose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueuePropose': grpc.unary_unary_rpc_method_handler(
                    servicer.QueuePropose,
                    request_deserializer=queue__pb2.QueueRequest.FromString,
                    response_serializer=queue__pb2.QueueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'queue.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueuePropose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/queue.QueueService/QueuePropose',
            queue__pb2.QueueRequest.SerializeToString,
            queue__pb2.QueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
