# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\x12\x05queue\";\n\x0cQueueRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x10\n\x08len_data\x18\x03 \x01(\x05\"+\n\rQueueResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t2I\n\x0cQueueService\x12\x39\n\x0cQueuePropose\x12\x13.queue.QueueRequest\x1a\x14.queue.QueueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUEUEREQUEST']._serialized_start=22
  _globals['_QUEUEREQUEST']._serialized_end=81
  _globals['_QUEUERESPONSE']._serialized_start=83
  _globals['_QUEUERESPONSE']._serialized_end=126
  _globals['_QUEUESERVICE']._serialized_start=128
  _globals['_QUEUESERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
