# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import suggestion_pb2 as suggestion__pb2


class SuggestionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SuggestionPropose = channel.unary_unary(
                '/suggestion.SuggestionService/SuggestionPropose',
                request_serializer=suggestion__pb2.SuggestionRequest.SerializeToString,
                response_deserializer=suggestion__pb2.SuggestionResponse.FromString,
                )


class SuggestionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SuggestionPropose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SuggestionPropose': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestionPropose,
                    request_deserializer=suggestion__pb2.SuggestionRequest.FromString,
                    response_serializer=suggestion__pb2.SuggestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suggestion.SuggestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuggestionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SuggestionPropose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suggestion.SuggestionService/SuggestionPropose',
            suggestion__pb2.SuggestionRequest.SerializeToString,
            suggestion__pb2.SuggestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
