# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import payment_pb2 as payment__pb2


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PaymentPreparer = channel.unary_unary(
                '/payment.PaymentService/PaymentPreparer',
                request_serializer=payment__pb2.PaymentPrepare.SerializeToString,
                response_deserializer=payment__pb2.PaymentResponse.FromString,
                )
        self.PaymentCommiter = channel.unary_unary(
                '/payment.PaymentService/PaymentCommiter',
                request_serializer=payment__pb2.PaymentCommit.SerializeToString,
                response_deserializer=payment__pb2.PaymentResponse.FromString,
                )


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PaymentPreparer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PaymentCommiter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PaymentPreparer': grpc.unary_unary_rpc_method_handler(
                    servicer.PaymentPreparer,
                    request_deserializer=payment__pb2.PaymentPrepare.FromString,
                    response_serializer=payment__pb2.PaymentResponse.SerializeToString,
            ),
            'PaymentCommiter': grpc.unary_unary_rpc_method_handler(
                    servicer.PaymentCommiter,
                    request_deserializer=payment__pb2.PaymentCommit.FromString,
                    response_serializer=payment__pb2.PaymentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PaymentPreparer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/PaymentPreparer',
            payment__pb2.PaymentPrepare.SerializeToString,
            payment__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PaymentCommiter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment.PaymentService/PaymentCommiter',
            payment__pb2.PaymentCommit.SerializeToString,
            payment__pb2.PaymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
