# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"\x1d\n\x0ePaymentPrepare\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\rPaymentCommit\x12\x0b\n\x03key\x18\x01 \x01(\t\"/\n\x0fPaymentResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\x9b\x01\n\x0ePaymentService\x12\x44\n\x0fPaymentPreparer\x12\x17.payment.PaymentPrepare\x1a\x18.payment.PaymentResponse\x12\x43\n\x0fPaymentCommiter\x12\x16.payment.PaymentCommit\x1a\x18.payment.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYMENTPREPARE']._serialized_start=26
  _globals['_PAYMENTPREPARE']._serialized_end=55
  _globals['_PAYMENTCOMMIT']._serialized_start=57
  _globals['_PAYMENTCOMMIT']._serialized_end=85
  _globals['_PAYMENTRESPONSE']._serialized_start=87
  _globals['_PAYMENTRESPONSE']._serialized_end=134
  _globals['_PAYMENTSERVICE']._serialized_start=137
  _globals['_PAYMENTSERVICE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
