# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x08\x65xecutor\">\n\x0f\x45xecutorRequest\x12\r\n\x05input\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x10\n\x08len_data\x18\x03 \x01(\x05\".\n\x10\x45xecutorResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t2[\n\x0f\x45xecutorService\x12H\n\x0f\x45xecutorPropose\x12\x19.executor.ExecutorRequest\x1a\x1a.executor.ExecutorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTORREQUEST']._serialized_start=28
  _globals['_EXECUTORREQUEST']._serialized_end=90
  _globals['_EXECUTORRESPONSE']._serialized_start=92
  _globals['_EXECUTORRESPONSE']._serialized_end=138
  _globals['_EXECUTORSERVICE']._serialized_start=140
  _globals['_EXECUTORSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
